[package]
name = "tdn"
version = "0.0.1"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[dependencies]
async-std = { version = "1", features = ["unstable"] }
futures = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"
bincode = "1"
toml = "0.5"
sha3 = "0.8"
rand = "0.7"

# JSONRPC
tide = "0.5"
mime = "0.3"

chamomile = { path = "../chamomile" } # Dev

[dev-dependencies]
tdn_permission = { path = "../TDN-Permission" } # Dev
