[package]
name = "tdn"
version = "0.0.1"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[features]
default = ["dev"]
dev = []

[dependencies]
async-std = { version = "1", features = ["unstable"] }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
lazy_static = "1"
toml = "0.5"
sha3 = "0.8"
rand = "0.7"
dirs = "2"
log = "0.4"

chamomile = { path = "../chamomile" }

# JSON-RPC
httparse = "1"
mime = "0.3"
async-tungstenite = "0.4"

[dev-dependencies]
tdn_permission = { path = "../TDN-Permission" } # Dev
