[package]
name = "tdn"
version = "0.0.1"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[workspace]
members = [
    "core",
    "crypto",
    "p2p",
    "rpc",
    "permission",
    "storage/distribute",
    "storage/keystore",
    "consensus/gossip",
    "consensus/pbft",
]

[dependencies]
core = { path = "./core" }
tdn_crypto = { path = "./crypto" }
tdn_p2p = { path = "./p2p" }
tdn_rpc = { path = "./rpc" }
tdn_permission = { path = "./permission" }
tdn_ds = { path = "./storage/distribute" }
tdn_keystore = { path  = "./storage/keystore" }
tdn_gossip = { path = "./consensus/gossip" }
tdn_pbft = { path = "./consensus/pbft" }
