[package]
name = "tdn"
version = "0.2.0"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[workspace]
members = [
    "types",
]

[features]
default = ["dev"]
dev = []

[dependencies]
#tdn_types = "0.3"
tdn_types = { path = "./types" }
futures = "0.3"
smol = "1.0"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"]}
serde_json = "1"
postcard = { version = "0.5", default-features = false, features = ["alloc"] }
toml = "0.5"
rand = "0.7"
log = "0.4"
httparse = "1"
mime = "0.3"
async-tungstenite = { version = "0.4", default-features = false }
#chamomile = "0.3"
chamomile = { path = "../chamomile" }

[dev-dependencies]
tdn_permission = "0.2"
