[package]
name = "tdn_types"
version = "0.3.0"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[dependencies]
#chamomile_types = "0.3"
chamomile_types = { path = "../../chamomile/types" } # Dev
async-channel = "1.5"
lazy_static = "1"
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"]}
serde_json = { version = "1.0", default-features = false, features = ["alloc"]}
sha3 = "0.9"
dirs = "3"
