[package]
name = "tdn_types"
version = "0.2.0"
authors = ["Contact <contact@cypherlink.io>"]
edition = "2018"
readme = "README.md"
description = "Trusted Distributed Network. (Another Blockchain infrastructure framework)."
repository = "https://github.com/cypherlink/TDN"
keywords = ["distributed", "blockchain", "infrastructure", "framework"]
license = "MIT/Apache-2.0"

[dependencies]
chamomile_types = "0.2"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha3 = "0.9"
dirs = "2"
